--1. NGUOI_DUNG
CREATE TABLE NGUOI_DUNG
(
    MaNguoiDung   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HoTen         NVARCHAR2(255)       NOT NULL,
    Email         VARCHAR2(100) UNIQUE NOT NULL,
    SoDienThoai   VARCHAR2(15) UNIQUE  NOT NULL,
    DaXacThuc     NUMBER(1) DEFAULT 0 NOT NULL CHECK (DaXacThuc IN (0, 1)),
    NgayTao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--2. TAI_KHOAN
CREATE TABLE TAI_KHOAN
(
    MaTaiKhoan     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNguoiDung    NUMBER REFERENCES NGUOI_DUNG (MaNguoiDung),
    TenDangNhap    VARCHAR2(50)  NOT NULL UNIQUE,
    MatKhauDaMaHoa VARCHAR2(255) NOT NULL,
    TenAnhDaiDien  NVARCHAR2(500), --Them BLOB voi kieu du lieu anh
    KieuDuLieuAnh  VARCHAR2(50), -- Lưu kiểu (image/jpeg, image/png)
    DuLieuAnh      BLOB,
    TrangThai      NVARCHAR2(20) DEFAULT N'Đang hoạt động' CHECK (TrangThai IN (N'Đang hoạt động', N'Chưa hoạt động')),
    VaiTro         NVARCHAR2(20) CHECK (VaiTro IN (N'Admin', N'Nhân viên'))
);

--3. KHACH_HANG
CREATE TABLE KHACH_HANG
(
    MaKhachHang NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SoDienThoai VARCHAR2(15) UNIQUE NOT NULL,--luu them gmail(optional de co the thi lm khuyen mai + ML)
    Gmail       VARCHAR2(50) UNIQUE NOT NULL,
    HoTen       NVARCHAR2(100)
);

--4. LOAI_SAN_PHAM
CREATE TABLE LOAI_SAN_PHAM
(
    MaLoaiSanPham  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenLoaiSanPham NVARCHAR2(100) NOT NULL UNIQUE,
    TrangThai      NVARCHAR2(20) DEFAULT N'Đang sử dụng' CHECK (TrangThai IN (N'Đang sử dụng', N'Chưa sử dụng'))
);

--5. NHOM_TUY_CHON
CREATE TABLE NHOM_TUY_CHON
(
    MaNhomTuyChon  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNhomTuyChon NVARCHAR2(100) NOT NULL UNIQUE
);

--6. LOAI_NGUYEN_LIEU
CREATE TABLE LOAI_NGUYEN_LIEU
(
    MaLoaiNguyenLieu  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenLoaiNguyenLieu NVARCHAR2(100) NOT NULL
);

--7. CHUC_NANG
CREATE TABLE CHUC_NANG
(
    MaChucNang  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenChucNang NVARCHAR2(100) NOT NULL
);

--8. NHOM_QUYEN
CREATE TABLE NHOM_QUYEN
(
    MaNhomQuyen  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNhomQuyen NVARCHAR2(100) NOT NULL,
    MoTa         NVARCHAR2(255)
);

--9. KHUYEN_MAI
CREATE TABLE KHUYEN_MAI
(
    MaKhuyenMai NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaCode      VARCHAR2(50) UNIQUE NOT NULL,
    GiaTriGiam  NUMBER              NOT NULL CHECK (GiaTriGiam >= 0),
    NgayHetHan  DATE
);

--10. SAN_PHAM
CREATE TABLE SAN_PHAM
(
    MaSanPham     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaLoaiSanPham NUMBER        NOT NULL,
    TenSanPham    NVARCHAR2(100) NOT NULL,
    GiaCoBan      NUMBER        NOT NULL CHECK (GiaCoBan >= 0),
    TenAnhSanPham NVARCHAR2(500), --Them BLOB voi kieu du lieu anh
    KieuDuLieuAnh VARCHAR2(50), -- Lưu kiểu (image/jpeg, image/png)
    DuLieuAnh     BLOB,
    MoTa          NVARCHAR2(500),
    TrangThai     NVARCHAR2(20) DEFAULT N'Đang bán' CHECK (TrangThai IN (N'Đang bán', N'Tạm hết', N'Ngừng bán')),
    CONSTRAINT FK_SP_LOAI FOREIGN KEY (MaLoaiSanPham) REFERENCES LOAI_SAN_PHAM (MaLoaiSanPham)
);

--11. TUY_CHON
CREATE TABLE TUY_CHON
(
    MaTuyChon     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNhomTuyChon NUMBER        NOT NULL,
    TenTuyChon    NVARCHAR2(100) NOT NULL,
    GiaPhuThu     NUMBER       DEFAULT 0 CHECK (GiaPhuThu >= 0),
    TrangThai     NVARCHAR2(20) DEFAULT N'Đang sử dụng' CHECK (TrangThai IN (N'Đang sử dụng', N'Chưa sử dụng')),
    CONSTRAINT FK_TC_NHOM FOREIGN KEY (MaNhomTuyChon) REFERENCES NHOM_TUY_CHON (MaNhomTuyChon)
);

--12. NGUYEN_LIEU
CREATE TABLE NGUYEN_LIEU
(
    MaNguyenLieu     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaLoaiNguyenLieu NUMBER        NOT NULL,
    TenNguyenLieu    NVARCHAR2(100) NOT NULL,
    DonViTinh        NVARCHAR2(50),
    SoLuongTon       NUMBER DEFAULT 0 CHECK (SoLuongTon >= 0),
    NguongCanhBao    NUMBER DEFAULT 0 CHECK (NguongCanhBao >= 0),
    NhaCungCap       NVARCHAR2(100),
    CONSTRAINT FK_NL_LOAI FOREIGN KEY (MaLoaiNguyenLieu) REFERENCES LOAI_NGUYEN_LIEU (MaLoaiNguyenLieu)
);

--13. PHAM_VI_QUYEN
CREATE TABLE PHAM_VI_QUYEN
(
    MaPhamVi   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenPhamVi  NVARCHAR2 (100) NOT NULL,
    MaChucNang NUMBER NOT NULL,
    Them       NUMBER(1) DEFAULT 0 CHECK (Them IN (0, 1)),
    Sua        NUMBER(1) DEFAULT 0 CHECK (Sua IN (0, 1)),
    Xoa        NUMBER(1) DEFAULT 0 CHECK (Xoa IN (0, 1)),
    Xem        NUMBER(1) DEFAULT 0 CHECK (Xem IN (0, 1)),
    XuatFile   NUMBER(1) DEFAULT 0 CHECK (XuatFile IN (0, 1)),
    CONSTRAINT FK_PV_CN FOREIGN KEY (MaChucNang) REFERENCES CHUC_NANG (MaChucNang)
);

--14. CONG_THUC
CREATE TABLE CONG_THUC
(
    MaSanPham    NUMBER,
    MaNguyenLieu NUMBER,
    SoLuongCan   NUMBER NOT NULL CHECK (SoLuongCan > 0),
    PRIMARY KEY (MaSanPham, MaNguyenLieu),
    FOREIGN KEY (MaSanPham) REFERENCES SAN_PHAM (MaSanPham),
    FOREIGN KEY (MaNguyenLieu) REFERENCES NGUYEN_LIEU (MaNguyenLieu)
);

--15. PHIEU_NHAP_KHO
CREATE TABLE PHIEU_NHAP_KHO
(
    MaPhieuNhap NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan  NUMBER NOT NULL,
    NgayNhap    DATE DEFAULT SYSDATE,
    TongGiaTri  NUMBER CHECK (TongGiaTri >= 0),
    GhiChu      NVARCHAR2(255),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan)
);

--16. CHI_TIET_PHIEU_NHAP
CREATE TABLE CHI_TIET_PHIEU_NHAP
(
    MaPhieuNhap  NUMBER,
    MaNguyenLieu NUMBER,
    SoLuong      NUMBER NOT NULL CHECK (SoLuong > 0),
    DonGia       NUMBER NOT NULL CHECK (DonGia >= 0),
    PRIMARY KEY (MaPhieuNhap, MaNguyenLieu),
    FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEU_NHAP_KHO (MaPhieuNhap),
    FOREIGN KEY (MaNguyenLieu) REFERENCES NGUYEN_LIEU (MaNguyenLieu)
);

--17. DON_HANG
CREATE TABLE DON_HANG
(
    MaDonHang           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaKhachHang         NUMBER,
    MaTaiKhoan          NUMBER,
    MaKhuyenMai         NUMBER,
    NgayDat             DATE         DEFAULT SYSDATE,
    TongTien            NUMBER CHECK (TongTien >= 0),
    SoTienGiam          NUMBER       DEFAULT 0 CHECK (SoTienGiam >= 0),
    ThanhTien           NUMBER CHECK (ThanhTien >= 0),
    PhuongThucThanhToan NVARCHAR2(50),
    TrangThai           NVARCHAR2(30) DEFAULT N'Chờ tiếp nhận' NOT NULL CHECK (TrangThai IN
                                                                          (N'Chờ tiếp nhận', N'Đang pha chế',
                                                                           N'Chờ thanh toán', N'Thành công',
                                                                           N'Thất bại')),
    GhiChu              NVARCHAR2(255),
    FOREIGN KEY (MaKhachHang) REFERENCES KHACH_HANG (MaKhachHang),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan),
    FOREIGN KEY (MaKhuyenMai) REFERENCES KHUYEN_MAI (MaKhuyenMai)
);

--18. CHI_TIET_DON_HANG
CREATE TABLE CHI_TIET_DON_HANG
(
    MaChiTietDon        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDonHang           NUMBER NOT NULL,
    MaSanPham           NUMBER NOT NULL,
    SoLuong             NUMBER NOT NULL CHECK (SoLuong > 0),
    GiaSanPhamSauPhuThu NUMBER NOT NULL CHECK (GiaSanPhamSauPhuThu >= 0),
    GhiChuMon           NVARCHAR2(255),
    FOREIGN KEY (MaDonHang) REFERENCES DON_HANG (MaDonHang),
    FOREIGN KEY (MaSanPham) REFERENCES SAN_PHAM (MaSanPham)
);

--19. CHI_TIET_TUY_CHON
CREATE TABLE CHI_TIET_TUY_CHON
(
    MaChiTietDon NUMBER,
    MaTuyChon    NUMBER,
    PRIMARY KEY (MaChiTietDon, MaTuyChon),
    FOREIGN KEY (MaChiTietDon) REFERENCES CHI_TIET_DON_HANG (MaChiTietDon),
    FOREIGN KEY (MaTuyChon) REFERENCES TUY_CHON (MaTuyChon)
);

--20. CHI_TIET_TUY_CHON_SAN_PHAM
CREATE TABLE CHI_TIET_TUY_CHON_SAN_PHAM
(
    MaSanPham    NUMBER,
    MaTuyChon    NUMBER,
    PRIMARY KEY (MaSanPham, MaTuyChon),
    FOREIGN KEY (MaSanPham) REFERENCES SAN_PHAM (MaSanPham),
    FOREIGN KEY (MaTuyChon) REFERENCES TUY_CHON (MaTuyChon)
);

--21. CAU_HINH_NHOM_QUYEN
CREATE TABLE CAU_HINH_NHOM_QUYEN
(
    MaNhomQuyen NUMBER,
    MaPhamVi    NUMBER,
    PRIMARY KEY (MaNhomQuyen, MaPhamVi),
    FOREIGN KEY (MaNhomQuyen) REFERENCES NHOM_QUYEN (MaNhomQuyen),
    FOREIGN KEY (MaPhamVi) REFERENCES PHAM_VI_QUYEN (MaPhamVi)
);

--22. PHAN_QUYEN_NHOM
CREATE TABLE PHAN_QUYEN_NHOM
(
    MaTaiKhoan  NUMBER,
    MaNhomQuyen NUMBER,
    PRIMARY KEY (MaTaiKhoan, MaNhomQuyen),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan),
    FOREIGN KEY (MaNhomQuyen) REFERENCES NHOM_QUYEN (MaNhomQuyen)
);

--23. PHAN_QUYEN_TAI_KHOAN
CREATE TABLE PHAN_QUYEN_TAI_KHOAN
(
    MaTaiKhoan NUMBER,
    MaPhamVi   NUMBER,
    PRIMARY KEY (MaTaiKhoan, MaPhamVi),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan),
    FOREIGN KEY (MaPhamVi) REFERENCES PHAM_VI_QUYEN (MaPhamVi)
);

--24. TOKEN_TAI_KHOAN
CREATE TABLE TOKEN_TAI_KHOAN
(
    MaToken        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan     NUMBER               NOT NULL,
    GiaTriToken    VARCHAR2(255) UNIQUE NOT NULL,
    ThoiDiemHetHan DATE,
    ThoiDiemCap    DATE      DEFAULT SYSDATE,
    DaThuHoi       NUMBER(1) DEFAULT 0 CHECK (DaThuHoi IN (0, 1)),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan)
);

--25. NHAT_KY_DANG_NHAP
CREATE TABLE NHAT_KY_DANG_NHAP
(
    MaLog              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan         NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    TenDangNhapNhapVao NVARCHAR2(100),
    ThoiGian           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TrangThai          NVARCHAR2(50) NOT NULL CHECK (TrangThai IN (N'Thành công', N'Thất bại')),
    LyDoThatBai        NVARCHAR2(255),
    DiaChiIP           VARCHAR2(45),
    UserAgent          VARCHAR2(500)
);

--26. NHAT_KY_HE_THONG
CREATE TABLE NHAT_KY_HE_THONG
(
    MaNhatKyHT       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan       NUMBER,
    HanhDong         VARCHAR2(50),
    TenBang          VARCHAR2(100),
    MaDoiTuong       NUMBER,
    DuLieuCu         CLOB,
    DuLieuMoi        CLOB,
    LyDo             NVARCHAR2(255),
    ThoiDiemThucHien DATE DEFAULT SYSDATE,
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan)
);

CREATE OR REPLACE PROCEDURE SP_DANG_KY_TAI_KHOAN (
    p_HoTen        IN NGUOI_DUNG.HoTen%Type,
    p_Email        IN NGUOI_DUNG.Email%type,
    p_SoDienThoai  IN NGUOI_DUNG.SoDienThoai%type,
    p_TenDangNhap  IN TAI_KHOAN.TenDangNhap%type,
    p_MatKhauMaHoa IN TAI_KHOAN.MatKhauDaMaHoa%type,

    --- Output
    p_KetQua       OUT NVARCHAR2
)
IS
    v_MaNguoiDung NGUOI_DUNG.MaNguoiDung%TYPE;
    v_MaTaiKhoan  NUMBER;
    v_Count       NUMBER;
BEGIN
    -- 1. Kiểm tra các dữ liệu UNIQUE bằng COUNT (Dành cho các luồng xử lý thông thường)
    SELECT COUNT(*) INTO v_Count FROM NGUOI_DUNG WHERE Email = p_Email;
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Email này đã được đăng ký.';
        RETURN;
    END IF;

    SELECT COUNT(*) INTO v_Count FROM NGUOI_DUNG WHERE SoDienThoai = p_SoDienThoai;
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Số điện thoại này đã được đăng ký.';
        RETURN;
    END IF;

    SELECT COUNT(*) INTO v_Count FROM TAI_KHOAN WHERE TenDangNhap = p_TenDangNhap;
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Tên đăng nhập đã tồn tại. Vui lòng chọn tên khác.';
        RETURN;
    END IF;

    -- 2. Insert dữ liệu
    INSERT INTO NGUOI_DUNG (HoTen, Email, SoDienThoai)
    VALUES (p_HoTen, p_Email, p_SoDienThoai)
    RETURNING MaNguoiDung INTO v_MaNguoiDung;

    INSERT INTO TAI_KHOAN (MaNguoiDung, TenDangNhap, MatKhauDaMaHoa)
    VALUES (v_MaNguoiDung, p_TenDangNhap, p_MatKhauMaHoa)
    RETURNING MaTaiKhoan INTO v_MaTaiKhoan;

    -- 4. Hoàn tất
    COMMIT;
    p_KetQua := N'Thành công';

EXCEPTION
    -- Bắt lỗi Race Condition (Nếu 2 request lọt qua vòng COUNT cùng lúc)
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
        p_KetQua := N'Lỗi: Thông tin (Email, SĐT hoặc Tên đăng nhập) đã tồn tại trong hệ thống do có giao dịch đồng thời.';

    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

INSERT INTO NHOM_QUYEN (TenNhomQuyen, MoTa)
VALUES (N'Nhân viên', N'Quyền cơ bản');

INSERT INTO NHOM_QUYEN (TenNhomQuyen, MoTa)
VALUES (N'Admin', N'Toàn quyền hệ thống');

INSERT INTO CHUC_NANG (TenChucNang) VALUES (N'Sản phẩm');
INSERT INTO CHUC_NANG (TenChucNang) VALUES (N'Đơn hàng');
INSERT INTO CHUC_NANG (TenChucNang) VALUES (N'Khách hàng');

-- Nhân viên: có quyền thêm, sửa, xóa, xem
INSERT INTO PHAM_VI_QUYEN (MaChucNang, Them, Sua, Xoa, Xem, XuatFile)
SELECT MaChucNang, 1, 1, 1, 1, 0 FROM CHUC_NANG;

-- Admin: full quyền
INSERT INTO PHAM_VI_QUYEN (MaChucNang, Them, Sua, Xoa, Xem, XuatFile)
SELECT MaChucNang, 1, 1, 1, 1, 1 FROM CHUC_NANG;

INSERT INTO CAU_HINH_NHOM_QUYEN (MaNhomQuyen, MaPhamVi)
SELECT 1, MaPhamVi
FROM PHAM_VI_QUYEN
WHERE XuatFile = 0;

INSERT INTO CAU_HINH_NHOM_QUYEN (MaNhomQuyen, MaPhamVi)
SELECT 2, MaPhamVi
FROM PHAM_VI_QUYEN
WHERE XuatFile = 1;

COMMIT;
DECLARE
    v_tmp  NVARCHAR2(200);
BEGIN
    SP_DANG_KY_TAI_KHOAN('HAOHAN', 'HAOHAO', '099999999', 'HAOHAO', 'HAOHAO', v_tmp);
    DBMS_OUTPUT.PUT_LINE(v_tmp);
end;

COMMIT;

SELECT * FROM TAI_KHOAN;
SELECT * FROM NGUOI_DUNG;
SELECT * FROM PHAN_QUYEN_NHOM;

-- 1. Tạo object chứa đầy đủ thông tin chi tiết và thông tin nguyên liệu
CREATE OR REPLACE TYPE T_CHI_TIET_PN_FULL AS OBJECT (
    MaNguyenLieu     NUMBER,          -- Truyền NULL (hoặc 0) nếu đây là nguyên liệu MỚI
    MaLoaiNguyenLieu NUMBER,          -- Bắt buộc nếu tạo mới
    TenNguyenLieu    NVARCHAR2(100),  -- Bắt buộc nếu tạo mới
    DonViTinh        NVARCHAR2(50),
    NhaCungCap       NVARCHAR2(100),
    SoLuong          NUMBER,
    DonGia           NUMBER
);
/

-- 2. Tạo mảng (Array) dựa trên object vừa tạo
CREATE OR REPLACE TYPE T_LIST_CHI_TIET_PN_FULL AS TABLE OF T_CHI_TIET_PN_FULL;
/

CREATE OR REPLACE PROCEDURE SP_LAP_PHIEU_NHAP_FULL (
    p_MaTaiKhoan      IN NUMBER,
    p_DanhSachChiTiet IN T_LIST_CHI_TIET_PN_FULL,
    p_NgayNhap        IN PHIEU_NHAP_KHO.NgayNhap%type,
    p_MaPhieuNhap_Out OUT NUMBER
)
AS
    v_TongGiaTri NUMBER := 0;
    v_MaNL_ThucTe NUMBER;
    v_Check_Ingredient NUMBER := 0;
BEGIN
    -- 1. TÍNH TỔNG GIÁ TRỊ PHIẾU NHẬP
    IF p_DanhSachChiTiet IS NOT NULL AND p_DanhSachChiTiet.COUNT > 0 THEN
        FOR i IN 1 .. p_DanhSachChiTiet.COUNT LOOP
            v_TongGiaTri := v_TongGiaTri + (p_DanhSachChiTiet(i).SoLuong * p_DanhSachChiTiet(i).DonGia);
        END LOOP;
    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Phiếu nhập phải có ít nhất 1 chi tiết nguyên liệu!');
    END IF;

    -- 2. INSERT VÀO BẢNG PHIẾU NHẬP (MASTER)
    INSERT INTO PHIEU_NHAP_KHO (MaTaiKhoan, NgayNhap, TongGiaTri)
    VALUES (1, p_NgayNhap, v_TongGiaTri)
    RETURNING MaPhieuNhap INTO p_MaPhieuNhap_Out;

    -- 3. XỬ LÝ NGUYÊN LIỆU VÀ CHI TIẾT
    FOR i IN 1 .. p_DanhSachChiTiet.COUNT LOOP

        -- A. Xử lý Nguyên Liệu (Tạo mới hoặc Cập nhật)
        -- Giả định từ Java: Nếu nguyên liệu mới, biến MaNguyenLieu truyền xuống là NULL hoặc 0
        SELECT COUNT(*) INTO v_Check_Ingredient
        FROM NGUYEN_LIEU NL
        WHERE UPPER(NL.TenNguyenLieu) = UPPER(p_DanhSachChiTiet(i).TenNguyenLieu);

        IF v_Check_Ingredient = 0 THEN

            -- Insert nguyên liệu mới và lấy ID tự tăng
            INSERT INTO NGUYEN_LIEU (
                MaLoaiNguyenLieu, TenNguyenLieu, DonViTinh, SoLuongTon, NhaCungCap
            ) VALUES (
                1,
                p_DanhSachChiTiet(i).TenNguyenLieu,
                p_DanhSachChiTiet(i).DonViTinh,
                p_DanhSachChiTiet(i).SoLuong, -- Tồn kho ban đầu chính là số lượng vừa nhập
                p_DanhSachChiTiet(i).NhaCungCap
            ) RETURNING MaNguyenLieu INTO v_MaNL_ThucTe;

        ELSE
            -- Nếu nguyên liệu đã tồn tại, dùng Mã truyền vào và cộng dồn số lượng
            SELECT NL2.MaNguyenLieu INTO v_MaNL_ThucTe
            FROM NGUYEN_LIEU NL2
            WHERE UPPER(NL2.TenNguyenLieu) = UPPER(p_DanhSachChiTiet(i).TENNGUYENLIEU)
            GROUP BY NL2.MaNguyenLieu
            FETCH FIRST 1 ROW ONLY;

            UPDATE NGUYEN_LIEU
            SET SoLuongTon = SoLuongTon + p_DanhSachChiTiet(i).SoLuong
            WHERE MaNguyenLieu = v_MaNL_ThucTe;

        END IF;

        -- B. Insert vào bảng Chi Tiết Phiếu Nhập
        -- Lưu ý: Dùng v_MaNL_ThucTe (Mã vừa sinh ra hoặc mã đã có)
        INSERT INTO CHI_TIET_PHIEU_NHAP (MaPhieuNhap, MaNguyenLieu, SoLuong, DonGia)
        VALUES (p_MaPhieuNhap_Out, v_MaNL_ThucTe, p_DanhSachChiTiet(i).SoLuong, p_DanhSachChiTiet(i).DonGia);

    END LOOP;

    -- Chốt giao dịch
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

insert into LOAI_NGUYEN_LIEU (MaLoaiNguyenLieu, TenLoaiNguyenLieu)
values (1, 'Cà phê');

commit;

select * from PHIEU_NHAP_KHO;
select * from NGUYEN_LIEU;
select * from CHI_TIET_PHIEU_NHAP;

select * from NGUOI_DUNG;
select * from tai_khoan;
SELECT * FROM TOKEN_TAI_KHOAN;
commit;
SELECT * FROM LOAI_SAN_PHAM;

SELECT MaPhieuNhap, NgayNhap, TK.MaTaiKhoan, TongGiaTri, ND.HoTen
FROM PHIEU_NHAP_KHO PNK
JOIN TAI_KHOAN TK on PNK.MaTaiKhoan = TK.MaTaiKhoan
JOIN NGUOI_DUNG ND ON TK.MaNguoiDung = ND.MaNguoiDung;

commit;

SELECT *
FROM TAI_KHOAN TK
JOIN NGUOI_DUNG ND ON TK.MaNguoiDung = ND.MaNguoiDung
WHERE TenDangNhap = 'camonanh' AND MatKhauDaMaHoa = '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b';

SELECT PNK.MaPhieuNhap, PNK.NgayNhap, TK.MaTaiKhoan, PNK.TongGiaTri
FROM PHIEU_NHAP_KHO PNK
         JOIN TAI_KHOAN TK
              ON PNK.MaTaiKhoan = TK.MaTaiKhoan;


SELECT * FROM PHIEU_NHAP_KHO;


DELETE FROM NGUYEN_LIEU
WHERE MaNguyenLieu IN (161, 162);

DELETE FROM CHI_TIET_PHIEU_NHAP
WHERE MaNguyenLieu IN (161, 162);

DELETE FROM PHIEU_NHAP_KHO
WHERE MaPhieuNhap IN (161);

SELECT * FROM PHIEU_NHAP_KHO;


CREATE OR REPLACE PROCEDURE SP_SUA_NGUYEN_LIEU (
    p_MaNguyenLieu IN NUMBER,
    p_TenMoi       IN NVARCHAR2,
    p_DvtMoi       IN NVARCHAR2,
    p_TonMoi       IN NUMBER,
    p_NguongMoi    IN NUMBER,
    p_MaTaiKhoan   IN NUMBER,
    p_LyDo         IN NVARCHAR2,
    p_KetQua       OUT NVARCHAR2
)
IS
    v_TenCu    NGUYEN_LIEU.TenNguyenLieu%TYPE;
    v_DvtCu    NGUYEN_LIEU.DonViTinh%TYPE;
    v_TonCu    NGUYEN_LIEU.SoLuongTon%TYPE;
    v_NguongCu NGUYEN_LIEU.NguongCanhBao%TYPE;
BEGIN
    -- 1. Lấy dữ liệu cũ hiện tại trong kho
    SELECT TenNguyenLieu, DonViTinh, SoLuongTon, NguongCanhBao
    INTO v_TenCu, v_DvtCu, v_TonCu, v_NguongCu
    FROM NGUYEN_LIEU
    WHERE MaNguyenLieu = p_MaNguyenLieu;

    -- 2. Kiểm tra và Ghi log cho từng trường bị thay đổi
    IF v_TenCu != p_TenMoi THEN
        INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong, DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
        VALUES (p_MaTaiKhoan, N'Sửa dữ liệu', 'NGUYEN_LIEU', p_MaNguyenLieu, v_TenCu, p_TenMoi, p_LyDo, SYSDATE);
    END IF;

    IF v_DvtCu != p_DvtMoi THEN
        INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong, DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
        VALUES (p_MaTaiKhoan, N'Sửa dữ liệu', 'NGUYEN_LIEU', p_MaNguyenLieu, v_DvtCu, p_DvtMoi, p_LyDo, SYSDATE);
    END IF;

    IF v_TonCu != p_TonMoi THEN
        INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong, DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
        VALUES (p_MaTaiKhoan, N'Sửa dữ liệu', 'NGUYEN_LIEU', p_MaNguyenLieu, TO_CHAR(v_TonCu), TO_CHAR(p_TonMoi), p_LyDo, SYSDATE);
    END IF;

    IF v_NguongCu != p_NguongMoi THEN
        INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong, DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
        VALUES (p_MaTaiKhoan, N'Sửa dữ liệu', 'NGUYEN_LIEU', p_MaNguyenLieu, TO_CHAR(v_NguongCu), TO_CHAR(p_NguongMoi), p_LyDo, SYSDATE);
    END IF;

    -- 3. Cập nhật dữ liệu mới vào bảng Nguyên Liệu
    UPDATE NGUYEN_LIEU
    SET TenNguyenLieu = p_TenMoi,
        DonViTinh = p_DvtMoi,
        SoLuongTon = p_TonMoi,
        NguongCanhBao = p_NguongMoi
    WHERE MaNguyenLieu = p_MaNguyenLieu;

    COMMIT;
    p_KetQua := N'Thành công';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_XOA_NGUYEN_LIEU (
    p_MaNguyenLieu IN NUMBER,
    p_MaTaiKhoan   IN NUMBER,
    p_LyDo         IN NVARCHAR2,
    p_KetQua       OUT NVARCHAR2
)
IS
    v_DuLieuCu CLOB;
BEGIN
    SELECT 'Tên: ' || TenNguyenLieu || '; ĐVT: ' || DonViTinh || '; Tồn kho: ' || SoLuongTon || '; Ngưỡng: ' || NguongCanhBao
    INTO v_DuLieuCu
    FROM NGUYEN_LIEU
    WHERE MaNguyenLieu = p_MaNguyenLieu;

    INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong,
                                    DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
    VALUES (p_MaTaiKhoan, 'Xóa dữ liệu', 'NGUYEN_LIEU', p_MaNguyenLieu,
            v_DuLieuCu, NULL, p_LyDo, CURRENT_TIMESTAMP);

    -- 3. Thực hiện xóa dữ liệu
    DELETE FROM CHI_TIET_PHIEU_NHAP
    WHERE MaNguyenLieu = p_MaNguyenLieu;

    DELETE FROM CONG_THUC
    WHERE MaNguyenLieu = p_MaNguyenLieu;

    DELETE FROM NGUYEN_LIEU
    WHERE MaNguyenLieu = p_MaNguyenLieu;

    COMMIT;
    p_KetQua := 'Thành công';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := 'Lỗi hệ thống: ' || SQLERRM;
END;
/

SELECT * FROM NHAT_KY_HE_THONG;

SELECT * FROM NGUYEN_LIEU;

CREATE OR REPLACE PROCEDURE SP_XOA_PHIEU_NHAP (
    p_MaPhieuNhap IN NUMBER,
    p_MaTaiKhoan  IN NUMBER,
    p_LyDo        IN NVARCHAR2,
    p_KetQua      OUT NVARCHAR2
)
IS
    v_DuLieuCu   CLOB;
    v_NgayNhap   DATE;
    v_TongGiaTri NUMBER;
    v_GhiChu     VARCHAR2(255);
    v_Count      NUMBER;
BEGIN
    -- 0. Kiểm tra phiếu nhập có tồn tại không (Ví dụ có 2 người cùng thao tác)
    SELECT COUNT(*) INTO v_Count
    FROM PHIEU_NHAP_KHO
    WHERE MaPhieuNhap = p_MaPhieuNhap;

    IF v_Count = 0 THEN
        p_KetQua := N'Lỗi: Không tìm thấy phiếu nhập này trong hệ thống.';
        RETURN;
    END IF;

    -- 1. Trích xuất thông tin Phiếu nhập để làm dữ liệu cũ (DuLieuCu)
    SELECT NgayNhap, TongGiaTri, GhiChu
    INTO v_NgayNhap, v_TongGiaTri, v_GhiChu
    FROM PHIEU_NHAP_KHO
    WHERE MaPhieuNhap = p_MaPhieuNhap;

    v_DuLieuCu := 'Ngày nhập: ' || TO_CHAR(v_NgayNhap, 'DD/MM/YYYY') ||
                  '; Tổng tiền: ' || v_TongGiaTri ||
                  '; Ghi chú: ' || v_GhiChu;

    -- 2. Ghi Log hệ thống
    INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong,
                                DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
    VALUES (p_MaTaiKhoan, N'Xóa dữ liệu', 'PHIEU_NHAP_KHO', p_MaPhieuNhap,
                v_DuLieuCu, NULL, p_LyDo, CURRENT_TIMESTAMP);

    -- 3. Cập nhật lại số lượng tồn kho (QUAN TRỌNG: Lấy số lượng từ phiếu nhập để trừ đi)
    FOR item IN (SELECT MaNguyenLieu, SoLuong
                 FROM CHI_TIET_PHIEU_NHAP
                 WHERE MaPhieuNhap = p_MaPhieuNhap)
    LOOP
        UPDATE NGUYEN_LIEU
        SET SoLuongTon = SoLuongTon - item.SoLuong
        WHERE MaNguyenLieu = item.MaNguyenLieu;
    END LOOP;

    -- 4. Xóa dữ liệu ở bảng con (Chi tiết phiếu nhập)
    DELETE FROM CHI_TIET_PHIEU_NHAP
    WHERE MaPhieuNhap = p_MaPhieuNhap;

    -- 5. Xóa dữ liệu ở bảng cha (Phiếu nhập kho)
    DELETE FROM PHIEU_NHAP_KHO
    WHERE MaPhieuNhap = p_MaPhieuNhap;

    -- Hoàn tất giao dịch
    COMMIT;
    p_KetQua := N'Thành công';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        -- Nếu việc trừ tồn kho làm cho số lượng bị âm (vi phạm CHECK constraint SoLuongTon >= 0), nó sẽ báo lỗi tại đây và rollback toàn bộ.
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

SELECT * FROM PHIEU_NHAP_KHO;

SELECT * FROM NHAT_KY_HE_THONG;


SELECT * FROM NGUYEN_LIEU NL
LEFT JOIN CHI_TIET_PHIEU_NHAP CTPN
ON NL.MaNguyenLieu = CTPN.MaNguyenLieu;

SELECT *
FROM SAN_PHAM SP
JOIN LOAI_SAN_PHAM LSP on SP.MaLoaiSanPham = LSP.MaLoaiSanPham;

SELECT * FROM LOAI_SAN_PHAM;
INSERT INTO LOAI_SAN_PHAM (TenLoaiSanPham) values ('Truyền thống');

INSERT INTO LOAI_SAN_PHAM (TenLoaiSanPham) values ('Đá xay');
commit;

INSERT INTO NHOM_TUY_CHON (TenNhomTuyChon) VALUES ('TOPPING');
INSERT INTO NHOM_TUY_CHON (TenNhomTuyChon) VALUES ('ĐÁ');
commit;

SELECT MaTuyChon, TenTuyChon, GiaPhuThu, TrangThai, N.MaNhomTuyChon, TenNhomTuyChon FROM NHOM_TUY_CHON N JOIN TUY_CHON T ON T.MaNhomTuyChon = N.MaNhomTuyChon;

INSERT INTO TUY_CHON(MaNhomTuyChon, TenTuyChon, GiaPhuThu) VALUES (1, 'TRÂN CHÂU HOÀNG KIM', 7000);
INSERT INTO TUY_CHON(MaNhomTuyChon, TenTuyChon, GiaPhuThu) VALUES (2, 'Ít đá', 0);

UPDATE LOAI_SAN_PHAM
SET TENLOAISANPHAM = 'Đá xay'
WHERE MaLoaiSanPham = 2;
INSERT INTO SAN_PHAM (MALOAISANPHAM, TENSANPHAM, GIACOBAN, TENANHSANPHAM, KIEUDULIEUANH, DULIEUANH) values (1, 'Trà sữa', 1000, null, null, null);

CREATE OR REPLACE PROCEDURE SP_INSERT_SAN_PHAM (
    p_TenSanPham      IN SAN_PHAM.TenSanPham%TYPE,
    p_GiaCoBan        IN SAN_PHAM.GiaCoBan%TYPE,
    p_TenAnhSanPham   IN SAN_PHAM.TenAnhSanPham%TYPE,
    p_KieuDuLieuAnh   IN SAN_PHAM.KieuDuLieuAnh%TYPE,
    p_DuLieuAnh       IN BLOB,
    p_TrangThai       IN SAN_PHAM.TrangThai%TYPE,
    p_TenLoaiSanPham  IN LOAI_SAN_PHAM.TenLoaiSanPham%type,
    p_MaSanPham_OUT   OUT SAN_PHAM.MaSanPham%TYPE
)
AS
    v_MaLoaiSanPham LOAI_SAN_PHAM.MaLoaiSanPham%type;
BEGIN
    SELECT MaLoaiSanPham INTO v_MaLoaiSanPham
    FROM LOAI_SAN_PHAM
    WHERE TenLoaiSanPham = p_TenLoaiSanPham;

    INSERT INTO SAN_PHAM (
        MaLoaiSanPham, TenSanPham, GiaCoBan, TenAnhSanPham,
        KieuDuLieuAnh, DuLieuAnh, TrangThai
    )
    VALUES (
        v_MaLoaiSanPham, p_TenSanPham, p_GiaCoBan, p_TenAnhSanPham,
        p_KieuDuLieuAnh, p_DuLieuAnh, p_TrangThai
    )
    RETURNING MaSanPham INTO p_MaSanPham_OUT; -- Lấy ID vừa insert

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_CT_TUY_CHON (
    p_MaSanPham       IN NUMBER,
    p_TenTuyChon      IN VARCHAR2,
    p_TenNhomTuyChon  IN VARCHAR2
)
AS
    v_MaTuyChon NUMBER;
BEGIN
    -- Tìm mã tùy chọn dựa trên Tên tùy chọn và Tên nhóm
    BEGIN
        SELECT T.MaTuyChon INTO v_MaTuyChon
        FROM TUY_CHON T
        JOIN NHOM_TUY_CHON N ON T.MaNhomTuyChon = N.MaNhomTuyChon
        WHERE T.TenTuyChon = p_TenTuyChon
          AND N.TenNhomTuyChon = p_TenNhomTuyChon;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_MaTuyChon := NULL; -- Nếu không có thì gán NULL
    END;

    -- Chỉ Insert nếu tìm thấy mã hợp lệ
    IF v_MaTuyChon IS NOT NULL THEN
        INSERT INTO CHI_TIET_TUY_CHON_SAN_PHAM (MaSanPham, MaTuyChon)
        VALUES (p_MaSanPham, v_MaTuyChon);
    END IF;

    COMMIT;
END;
/

SELECT SP.MaSanPham,
                            SP.TenSanPham,
                            SP.TenAnhSanPham,
                           SP.KieuDuLieuAnh,
                             SP.TrangThai AS TrangThaiSP,
                             LSP.TenLoaiSanPham,
                             LSP.TrangThai AS TrangThaiLoai,
                             SP.GiaCoBan ,
                            SP.DuLieuAnh
                     FROM SAN_PHAM SP
                     JOIN LOAI_SAN_PHAM LSP on SP.MaLoaiSanPham = LSP.MaLoaiSanPham;

SELECT *
FROM CHI_TIET_TUY_CHON_SAN_PHAM;

INSERT INTO CHUC_NANG (TenChucNang) VALUES ('Quản lý phân quyền');

COMMIT;
UPDATE CHUC_NANG
SET TENCHUCNANG = 'Phân quyền'
WHERE MaChucNang = 5;

