--1. NGUOI_DUNG
CREATE TABLE NGUOI_DUNG
(
    MaNguoiDung NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HoTen       NVARCHAR2(255)       NOT NULL,
    Email       VARCHAR2(100) UNIQUE NOT NULL,
    SoDienThoai VARCHAR2(15) UNIQUE  NOT NULL,
    DaXacThuc   NUMBER(1) DEFAULT 0  NOT NULL CHECK (DaXacThuc IN (0, 1)),
    NgayTao     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--2. TAI_KHOAN
CREATE TABLE TAI_KHOAN
(
    MaTaiKhoan     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNguoiDung    NUMBER REFERENCES NGUOI_DUNG (MaNguoiDung),
    TenDangNhap    VARCHAR2(50)  NOT NULL UNIQUE,
    MatKhauDaMaHoa VARCHAR2(255) NOT NULL,
    TenAnhDaiDien  NVARCHAR2(500), --Them BLOB voi kieu du lieu anh
    KieuDuLieuAnh  VARCHAR2(50),   -- Lưu kiểu (image/jpeg, image/png)
    DuLieuAnh      BLOB,
    TrangThai      NVARCHAR2(20) DEFAULT N'Đang hoạt động' CHECK (TrangThai IN (N'Đang hoạt động', N'Bị khoá')),
    DangNhapLanDau NUMBER(1) DEFAULT 0 NOT NULL CHECK (DangNhapLanDau IN (0, 1))
);

-- Bảng quản lý Hạng Thành Viên
CREATE TABLE HANG_THANH_VIEN (
    MaHang NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenHang NVARCHAR2(50) UNIQUE NOT NULL,
    DiemYeuCau NUMBER DEFAULT 0 NOT NULL,
    PhanTramChietKhau NUMBER(5,2) DEFAULT 0 CHECK (PhanTramChietKhau >= 0 AND PhanTramChietKhau <= 100),
    LaMacDinh NUMBER(1) DEFAULT 0 CHECK (LaMacDinh IN (0, 1)) -- Chỉ duy nhất 1 dòng được là 1 (Hạng khởi điểm)
);

--3. KHACH_HANG
CREATE TABLE KHACH_HANG
(
    MaKhachHang NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SoDienThoai VARCHAR2(15) UNIQUE NOT NULL,
    HoTen       NVARCHAR2(100),
    NgayDangKy    DATE DEFAULT SYSDATE,
    DiemTichLuy NUMBER DEFAULT 0 NOT NULL,
    DiemHienTai NUMBER DEFAULT 0 NOT NULL,
    MaHang NUMBER REFERENCES HANG_THANH_VIEN(MaHang),
    CONSTRAINT CHK_Diem_HopLe CHECK (DiemHienTai >= 0 AND DiemHienTai <= DiemTichLuy)
);

-- Bảng Cấu hình tỷ lệ (Chỉ có 1 dòng duy nhất)
CREATE TABLE CAU_HINH_QUY_DOI (
    TienTichMotDiem NUMBER NOT NULL, -- Ví dụ: 10000 (10k = 1 điểm)
    GiaTriMotDiem NUMBER NOT NULL,    -- Ví dụ: 100 (1 điểm = 100đ khi thanh toán)
    DiemDoiMotLy NUMBER DEFAULT 50 NOT NULL
);

-- 1. Thêm dữ liệu khởi tạo bắt buộc
INSERT INTO HANG_THANH_VIEN (TenHang, DiemYeuCau, PhanTramChietKhau, LaMacDinh) VALUES (N'Thành viên', 0, 0, 1);
INSERT INTO CAU_HINH_QUY_DOI (TienTichMotDiem, GiaTriMotDiem) VALUES (10000, 100);
COMMIT;

-- 2. SP Xóa Hạng (Luồng S-2: Chuyển khách về hạng mặc định)
CREATE OR REPLACE PROCEDURE SP_XOA_HANG_THANH_VIEN (
    p_MaHang IN NUMBER,
    p_KetQua OUT NVARCHAR2
) IS
    v_LaMacDinh NUMBER;
    v_MaMacDinh NUMBER;
BEGIN
    -- Kiểm tra xem có phải hạng mặc định không
    SELECT LaMacDinh INTO v_LaMacDinh FROM HANG_THANH_VIEN WHERE MaHang = p_MaHang;
    IF v_LaMacDinh = 1 THEN
        p_KetQua := N'Lỗi: Không thể xóa hạng Thành viên mặc định!';
        RETURN;
    END IF;

    -- Lấy Mã hạng của hạng Mặc định
    SELECT MaHang INTO v_MaMacDinh FROM HANG_THANH_VIEN WHERE LaMacDinh = 1 AND ROWNUM = 1;

    -- Chuyển toàn bộ khách hàng ở hạng bị xóa về hạng mặc định
    UPDATE KHACH_HANG SET MaHang = v_MaMacDinh WHERE MaHang = p_MaHang;

    -- Xóa hạng
    DELETE FROM HANG_THANH_VIEN WHERE MaHang = p_MaHang;

    COMMIT;
    p_KetQua := N'Thành công';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

-- 3. SP Đồng bộ thứ hạng (Luồng S-3: Tính toán lại hạng cho toàn bộ KH)
CREATE OR REPLACE PROCEDURE SP_DONG_BO_HANG_THANH_VIEN (
    p_KetQua OUT NVARCHAR2
) IS
BEGIN
    -- Sử dụng MERGE INTO và KEEP DENSE_RANK FIRST của Oracle để tìm Hạng cao nhất
    -- mà khách hàng đủ điều kiện, sau đó Update hàng loạt.
    MERGE INTO KHACH_HANG K
    USING (
        SELECT K_IN.MaKhachHang,
               (SELECT MAX(MaHang) KEEP (DENSE_RANK FIRST ORDER BY DiemYeuCau DESC)
                FROM HANG_THANH_VIEN
                WHERE DiemYeuCau <= K_IN.DiemTichLuy) AS NewMaHang
        FROM KHACH_HANG K_IN
    ) T
    ON (K.MaKhachHang = T.MaKhachHang)
    WHEN MATCHED THEN
        UPDATE SET K.MaHang = T.NewMaHang;

    COMMIT;
    p_KetQua := N'Thành công';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK; -- Fallback khi mất điện, đứt cáp giữa chừng
        p_KetQua := N'Quá trình đồng bộ bị gián đoạn do sự cố. Dữ liệu đã được khôi phục nguyên trạng.';
END;
/

--4. LOAI_SAN_PHAM
CREATE TABLE LOAI_SAN_PHAM
(
    MaLoaiSanPham  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenLoaiSanPham NVARCHAR2(100) NOT NULL UNIQUE,
    Thue_GTGT_MacDinh NUMBER(5, 2) DEFAULT 8,
    TrangThai      NVARCHAR2(20) DEFAULT N'Đang sử dụng' CHECK (TrangThai IN (N'Đang sử dụng', N'Đã ẩn'))
);

--5. NHOM_TUY_CHON
CREATE TABLE NHOM_TUY_CHON
(
    MaNhomTuyChon  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNhomTuyChon NVARCHAR2(100) NOT NULL UNIQUE
);

--6. LOAI_NGUYEN_LIEU
CREATE TABLE LOAI_NGUYEN_LIEU
(
    MaLoaiNguyenLieu  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenLoaiNguyenLieu NVARCHAR2(100) NOT NULL
);

--7. CHUC_NANG
CREATE TABLE CHUC_NANG
(
    MaChucNang  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenChucNang NVARCHAR2(100) NOT NULL
);

--8. NHOM_QUYEN
CREATE TABLE NHOM_QUYEN
(
    MaNhomQuyen  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNhomQuyen NVARCHAR2(100) NOT NULL,
    MoTa         NVARCHAR2(255)
);

--10. SAN_PHAM
CREATE TABLE SAN_PHAM
(
    MaSanPham     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaLoaiSanPham NUMBER         NOT NULL,
    TenSanPham    NVARCHAR2(100) NOT NULL,
    TenAnhSanPham NVARCHAR2(500), --Them BLOB voi kieu du lieu anh
    KieuDuLieuAnh VARCHAR2(50),   -- Lưu kiểu (image/jpeg, image/png)
    DuLieuAnh     BLOB,
    MoTa          NVARCHAR2(500),
    TrangThai     NVARCHAR2(20) DEFAULT N'Đang bán' CHECK (TrangThai IN (N'Đang bán', N'Tạm hết', N'Ngừng bán')),
    Thue_GTGT     NUMBER(5, 2) DEFAULT 8,
    CONSTRAINT FK_SP_LOAI FOREIGN KEY (MaLoaiSanPham) REFERENCES LOAI_SAN_PHAM (MaLoaiSanPham)
);

-- 3. Bảng Biến Thể Sản Phẩm (Size)
CREATE TABLE BIEN_THE (
    MaBienThe NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaSanPham NUMBER REFERENCES SAN_PHAM(MaSanPham),
    TenSize NVARCHAR2(20) NOT NULL,
    GiaTaiQuan NUMBER(15, 0) NOT NULL CHECK (GiaTaiQuan > 0),
    GiaMangVe NUMBER(15, 0) DEFAULT 0 CHECK (GiaMangVe >= 0),
    GiaNgayLe NUMBER(15, 0) DEFAULT 0 CHECK (GiaNgayLe >= 0)
);

--12. NGUYEN_LIEU
CREATE TABLE NGUYEN_LIEU
(
    MaNguyenLieu     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaLoaiNguyenLieu NUMBER        NOT NULL,
    TenNguyenLieu    VARCHAR2(100) NOT NULL,
    DonViTinh        VARCHAR2(50),
    SoLuongTon       NUMBER DEFAULT 0 CHECK (SoLuongTon >= 0),
    NguongCanhBao    NUMBER DEFAULT 0 CHECK (NguongCanhBao >= 0),
    Thue_GTGT NUMBER(5, 2) DEFAULT 8,
    DonGiaBinhQuan NUMBER(15, 2),
    DaXoa NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_NL_LOAI FOREIGN KEY (MaLoaiNguyenLieu) REFERENCES LOAI_NGUYEN_LIEU (MaLoaiNguyenLieu)
);

CREATE TABLE TOPPING (
    MaTopping NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenTopping NVARCHAR2(100) NOT NULL,
    GiaBan NUMBER(15, 0) NOT NULL CHECK (GiaBan >= 0),
    MaNguyenLieuTru NUMBER REFERENCES NGUYEN_LIEU(MaNguyenLieu),
    DinhLuongHaoHut NUMBER(10, 2),
    Thue_GTGT NUMBER(5, 2) DEFAULT 8
);

--13. PHAM_VI_QUYEN
CREATE TABLE PHAM_VI_QUYEN
(
    MaPhamVi   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenPhamVi  NVARCHAR2(100) NOT NULL,
    MaChucNang NUMBER         NOT NULL,
    Them       NUMBER(1) DEFAULT 0 CHECK (Them IN (0, 1)),
    Sua        NUMBER(1) DEFAULT 0 CHECK (Sua IN (0, 1)),
    Xoa        NUMBER(1) DEFAULT 0 CHECK (Xoa IN (0, 1)),
    Xem        NUMBER(1) DEFAULT 0 CHECK (Xem IN (0, 1)),
    XuatFile   NUMBER(1) DEFAULT 0 CHECK (XuatFile IN (0, 1)),
    CONSTRAINT FK_PV_CN FOREIGN KEY (MaChucNang) REFERENCES CHUC_NANG (MaChucNang)
);

--14. CONG_THUC
CREATE TABLE CONG_THUC
(
    MaBienThe    NUMBER,
    MaNguyenLieu NUMBER,
    SoLuongCan   NUMBER NOT NULL CHECK (SoLuongCan > 0),
    PRIMARY KEY (MaBienThe, MaNguyenLieu),
    FOREIGN KEY (MaBienThe) REFERENCES BIEN_THE (MaBienThe),
    FOREIGN KEY (MaNguyenLieu) REFERENCES NGUYEN_LIEU (MaNguyenLieu)
);

--15. PHIEU_NHAP_KHO
CREATE TABLE PHIEU_NHAP_KHO
(
    MaPhieuNhap NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan  NUMBER NOT NULL,
    NgayNhap    DATE DEFAULT SYSDATE,
    TongGiaTri  NUMBER CHECK (TongGiaTri >= 0),
    GhiChu      NVARCHAR2(255),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan)
);

-- 12. Lô Nguyên Liệu (Quản lý HSD và FEFO)
CREATE TABLE LO_NGUYEN_LIEU (
    MaLo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNguyenLieu NUMBER REFERENCES NGUYEN_LIEU(MaNguyenLieu),
    MaPhieuNhap NUMBER REFERENCES PHIEU_NHAP_KHO(MaPhieuNhap),
    NhaCungCap VARCHAR2(100),
    SoLuongBanDau NUMBER(15, 2),
    SoLuongConLai NUMBER(15, 2),
    DonGiaQuyDoi NUMBER(15, 2),
    HanSuDung DATE
);

--16. CHI_TIET_PHIEU_NHAP
CREATE TABLE CHI_TIET_PHIEU_NHAP
(
    MaPhieuNhap  NUMBER,
    MaNguyenLieu NUMBER,
    SoLuong      NUMBER NOT NULL CHECK (SoLuong > 0),
    GiaTruocThue NUMBER NOT NULL CHECK (GiaTruocThue >= 0),
    TienThue     NUMBER(15, 0),
    DinhLuong    NUMBER(10, 2),
    ThanhTien    NUMBER(15, 0),
    PRIMARY KEY (MaPhieuNhap, MaNguyenLieu),
    FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEU_NHAP_KHO (MaPhieuNhap),
    FOREIGN KEY (MaNguyenLieu) REFERENCES NGUYEN_LIEU (MaNguyenLieu)
);

-- 13. Phiếu Hủy Hàng
CREATE TABLE PHIEU_HUY_HANG (
    MaPhieuHuy NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NgayHuy DATE DEFAULT SYSDATE,
    GhiChu NVARCHAR2(255)
);

CREATE TABLE CT_PHIEU_HUY_HANG (
    MaPhieuHuy NUMBER REFERENCES PHIEU_HUY_HANG(MaPhieuHuy),
    MaLo NUMBER REFERENCES LO_NGUYEN_LIEU(MaLo),
    SoLuongHuy NUMBER(15, 2),
    LyDo NVARCHAR2(100),
    PRIMARY KEY (MaPhieuHuy, MaLo)
);


--17. DON_HANG
CREATE TABLE DON_HANG
(
    MaDonHang           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaKhachHang         NUMBER,
    MaTaiKhoan          NUMBER,

    NgayDat             DATE          DEFAULT SYSDATE,
    TongTien            NUMBER CHECK (TongTien >= 0),
    SoTienGiam          NUMBER        DEFAULT 0 CHECK (SoTienGiam >= 0),
    TongTienThue        NUMBER DEFAULT 0 CHECK (TongTienThue >= 0), -- Thêm mới để kế toán tính VAT
    ThanhTien           NUMBER CHECK (ThanhTien >= 0),              -- Lúc này ThanhTien = TongTien - SoTienGiam + TongTienThue
    PhuongThucThanhToan NVARCHAR2(50),
    TrangThaiPhaChe NVARCHAR2(30) DEFAULT N'Chờ tiếp nhận' NOT NULL
    CHECK (TrangThaiPhaChe IN (N'Chờ tiếp nhận', N'Đang pha chế', N'Đã hoàn thành', N'Đã hủy')),

    TrangThaiThanhToan NVARCHAR2(30) DEFAULT N'Chưa thanh toán' NOT NULL
    CHECK (TrangThaiThanhToan IN (N'Chưa thanh toán', N'Đã thanh toán', N'Đã hoàn tiền')),

    GhiChu              NVARCHAR2(255),
    DiemDaDung INT DEFAULT 0 CHECK (DiemDaDung >= 0),
    TienGiamGia NUMBER DEFAULT 0 CHECK (TienGiamGia >= 0),
    FOREIGN KEY (MaKhachHang) REFERENCES KHACH_HANG (MaKhachHang),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan)
);


--18. CHI_TIET_DON_HANG
CREATE TABLE CHI_TIET_DON_HANG (
    MaChiTietDon        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDonHang           NUMBER NOT NULL,
    MaBienThe           NUMBER NOT NULL,
    SoLuong             NUMBER NOT NULL CHECK (SoLuong > 0),
    GiaTruocThue        NUMBER NOT NULL CHECK (GiaTruocThue >= 0), -- Thay thế cột cũ
    TienThue            NUMBER(15, 0) DEFAULT 0,                   -- Thêm mới
    ThanhTien           NUMBER(15, 0) NOT NULL,                    -- Thêm mới (GiaTruocThue + TienThue) * SoLuong
    GhiChuMon           NVARCHAR2(255),
    FOREIGN KEY (MaDonHang) REFERENCES DON_HANG (MaDonHang),
    FOREIGN KEY (MaBienThe) REFERENCES BIEN_THE (MaBienThe)
);

CREATE TABLE CHI_TIET_TOPPING (
    MaCTHD NUMBER REFERENCES CHI_TIET_DON_HANG(MaChiTietDon),
    MaTopping NUMBER REFERENCES TOPPING(MaTopping),
    SoLuong NUMBER DEFAULT 1 CHECK (SoLuong > 0), -- Thêm cột này
    GiaTruocThue NUMBER(15, 0),
    TienThue NUMBER(15, 0),
    PRIMARY KEY (MaCTHD, MaTopping)
);

CREATE TABLE SAN_PHAM_TOPPING (
    MaSanPham NUMBER REFERENCES SAN_PHAM(MaSanPham),
    MaTopping NUMBER REFERENCES TOPPING(MaTopping),
    PRIMARY KEY (MaSanPham, MaTopping)
);

--21. CAU_HINH_NHOM_QUYEN
CREATE TABLE CAU_HINH_NHOM_QUYEN
(
    MaNhomQuyen NUMBER,
    MaPhamVi    NUMBER,
    PRIMARY KEY (MaNhomQuyen, MaPhamVi),
    FOREIGN KEY (MaNhomQuyen) REFERENCES NHOM_QUYEN (MaNhomQuyen),
    FOREIGN KEY (MaPhamVi) REFERENCES PHAM_VI_QUYEN (MaPhamVi)
);

--22. PHAN_QUYEN_NHOM
CREATE TABLE PHAN_QUYEN_NHOM
(
    MaTaiKhoan  NUMBER,
    MaNhomQuyen NUMBER,
    PRIMARY KEY (MaTaiKhoan, MaNhomQuyen),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan),
    FOREIGN KEY (MaNhomQuyen) REFERENCES NHOM_QUYEN (MaNhomQuyen)
);

--23. PHAN_QUYEN_TAI_KHOAN
CREATE TABLE PHAN_QUYEN_TAI_KHOAN
(
    MaTaiKhoan NUMBER,
    MaPhamVi   NUMBER,
    PRIMARY KEY (MaTaiKhoan, MaPhamVi),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan),
    FOREIGN KEY (MaPhamVi) REFERENCES PHAM_VI_QUYEN (MaPhamVi)
);

--24. TOKEN_TAI_KHOAN
CREATE TABLE TOKEN_TAI_KHOAN
(
    MaToken        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan     NUMBER               NOT NULL,
    GiaTriToken    VARCHAR2(255) UNIQUE NOT NULL,
    ThoiDiemHetHan DATE,
    ThoiDiemCap    DATE      DEFAULT SYSDATE,
    DaThuHoi       NUMBER(1) DEFAULT 0 CHECK (DaThuHoi IN (0, 1)),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan)
);

--25. NHAT_KY_DANG_NHAP
CREATE TABLE NHAT_KY_DANG_NHAP
(
    MaLog              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan         NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    TenDangNhapNhapVao NVARCHAR2(100),
    ThoiGian           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TrangThai          NVARCHAR2(50) NOT NULL CHECK (TrangThai IN (N'Thành công', N'Thất bại')),
    LyDoThatBai        NVARCHAR2(255),
    DiaChiIP           VARCHAR2(45),
    UserAgent          VARCHAR2(500)
);

--26. NHAT_KY_HE_THONG
CREATE TABLE NHAT_KY_HE_THONG
(
    MaNhatKyHT       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan       NUMBER,
    HanhDong         VARCHAR2(50),
    TenBang          VARCHAR2(100),
    MaDoiTuong       NUMBER,
    DuLieuCu         CLOB,
    DuLieuMoi        CLOB,
    LyDo             NVARCHAR2(255),
    ThoiDiemThucHien DATE DEFAULT SYSDATE,
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan)
);

CREATE OR REPLACE PROCEDURE SP_DANG_KY_TAI_KHOAN(
    p_HoTen IN NGUOI_DUNG.HoTen%Type,
    p_Email IN NGUOI_DUNG.Email%type,
    p_SoDienThoai IN NGUOI_DUNG.SoDienThoai%type,
    p_TenDangNhap IN TAI_KHOAN.TenDangNhap%type,
    p_MatKhauMaHoa IN TAI_KHOAN.MatKhauDaMaHoa%type,

    --- Output
    p_KetQua OUT NVARCHAR2
)
    IS
    v_MaNguoiDung NGUOI_DUNG.MaNguoiDung%TYPE;
    v_MaTaiKhoan  NUMBER;
    v_Count       NUMBER;
BEGIN
    -- 1. Kiểm tra các dữ liệu UNIQUE bằng COUNT (Dành cho các luồng xử lý thông thường)
    SELECT COUNT(*) INTO v_Count FROM NGUOI_DUNG WHERE Email = p_Email;
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Email này đã được đăng ký.';
        RETURN;
    END IF;

    SELECT COUNT(*) INTO v_Count FROM NGUOI_DUNG WHERE SoDienThoai = p_SoDienThoai;
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Số điện thoại này đã được đăng ký.';
        RETURN;
    END IF;

    SELECT COUNT(*) INTO v_Count FROM TAI_KHOAN WHERE TenDangNhap = p_TenDangNhap;
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Tên đăng nhập đã tồn tại. Vui lòng chọn tên khác.';
        RETURN;
    END IF;

    -- 2. Insert dữ liệu
    INSERT INTO NGUOI_DUNG (HoTen, Email, SoDienThoai)
    VALUES (p_HoTen, p_Email, p_SoDienThoai)
    RETURNING MaNguoiDung INTO v_MaNguoiDung;

    INSERT INTO TAI_KHOAN (MaNguoiDung, TenDangNhap, MatKhauDaMaHoa)
    VALUES (v_MaNguoiDung, p_TenDangNhap, p_MatKhauMaHoa)
    RETURNING MaTaiKhoan INTO v_MaTaiKhoan;

    -- 4. Hoàn tất
    COMMIT;
    p_KetQua := N'Thành công';

EXCEPTION
    -- Bắt lỗi Race Condition (Nếu 2 request lọt qua vòng COUNT cùng lúc)
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
        p_KetQua :=
                N'Lỗi: Thông tin (Email, SĐT hoặc Tên đăng nhập) đã tồn tại trong hệ thống do có giao dịch đồng thời.';

    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SUA_TAI_KHOAN_NV(
    p_MaTaiKhoan IN NUMBER,
    p_HoTen IN NGUOI_DUNG.HoTen%Type,
    p_Email IN NGUOI_DUNG.Email%type,
    p_SoDienThoai IN NGUOI_DUNG.SoDienThoai%type,

    --- Output
    p_KetQua OUT NVARCHAR2
)
IS
    v_MaNguoiDung NGUOI_DUNG.MaNguoiDung%TYPE;
    v_Count NUMBER;
BEGIN
    -- Lấy Mã Người Dùng
    SELECT MaNguoiDung INTO v_MaNguoiDung FROM TAI_KHOAN WHERE MaTaiKhoan = p_MaTaiKhoan;

    -- Kiểm tra Email trùng (loại trừ user hiện tại)
    SELECT COUNT(*) INTO v_Count FROM NGUOI_DUNG WHERE Email = p_Email AND MaNguoiDung <> v_MaNguoiDung;
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Email này đã được đăng ký cho người khác.';
        RETURN;
    END IF;

    -- Kiểm tra SĐT trùng
    SELECT COUNT(*) INTO v_Count FROM NGUOI_DUNG WHERE SoDienThoai = p_SoDienThoai AND MaNguoiDung <> v_MaNguoiDung;
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Số điện thoại này đã được đăng ký cho người khác.';
        RETURN;
    END IF;

    -- Cập nhật thông tin
    UPDATE NGUOI_DUNG
    SET HoTen = p_HoTen, Email = p_Email, SoDienThoai = p_SoDienThoai
    WHERE MaNguoiDung = v_MaNguoiDung;

    COMMIT;
    p_KetQua := N'Thành công';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

COMMIT;

CREATE OR REPLACE PROCEDURE SP_THEM_NGUYEN_LIEU_GOC (
    p_TenLoai        IN NVARCHAR2,
    p_TenNguyenLieu  IN NVARCHAR2,
    p_DonViTinh      IN NVARCHAR2,
    p_NguongCanhBao  IN NUMBER,
    p_KetQua         OUT NVARCHAR2
)
IS
    v_MaLoai NUMBER;
    v_Count NUMBER;
BEGIN
    -- Kiểm tra trùng tên nguyên liệu
    SELECT COUNT(*) INTO v_Count FROM NGUYEN_LIEU WHERE UPPER(TenNguyenLieu) = UPPER(p_TenNguyenLieu);
    IF v_Count > 0 THEN
        p_KetQua := N'Lỗi: Tên nguyên liệu này đã tồn tại!';
        RETURN;
    END IF;

    -- Lấy mã loại nguyên liệu
    SELECT MaLoaiNguyenLieu INTO v_MaLoai FROM LOAI_NGUYEN_LIEU WHERE TenLoaiNguyenLieu = p_TenLoai;

    -- Insert vào bảng với Tồn Kho cứng bằng 0
    INSERT INTO NGUYEN_LIEU (MaLoaiNguyenLieu, TenNguyenLieu, DonViTinh, SoLuongTon, NguongCanhBao, Thue_GTGT, DonGiaBinhQuan)
    VALUES (v_MaLoai, p_TenNguyenLieu, p_DonViTinh, 0, p_NguongCanhBao, 8, 0);

    COMMIT;
    p_KetQua := N'Thành công';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_XUAT_HUY_LO (
    p_MaLo           IN NUMBER,
    p_SoLuongHuy     IN NUMBER,
    p_LyDo           IN NVARCHAR2,
    p_KetQua         OUT NVARCHAR2
)
IS
    v_MaPhieuHuy NUMBER;
    v_SoLuongTonLo NUMBER;
BEGIN
    -- 1. Kiểm tra tồn kho của lô
    SELECT SoLuongConLai INTO v_SoLuongTonLo FROM LO_NGUYEN_LIEU WHERE MaLo = p_MaLo;

    IF p_SoLuongHuy > v_SoLuongTonLo THEN
        p_KetQua := N'Lỗi: Số lượng hủy lớn hơn số lượng tồn của lô!';
        RETURN;
    END IF;

    -- 2. Tạo Phiếu hủy hàng
    INSERT INTO PHIEU_HUY_HANG (NgayHuy, GhiChu)
    VALUES (SYSDATE, N'Hủy từ màn hình Chi tiết kho')
    RETURNING MaPhieuHuy INTO v_MaPhieuHuy;

    -- 3. Ghi chi tiết phiếu hủy
    INSERT INTO CT_PHIEU_HUY_HANG (MaPhieuHuy, MaLo, SoLuongHuy, LyDo)
    VALUES (v_MaPhieuHuy, p_MaLo, p_SoLuongHuy, p_LyDo);

    -- 4. Trừ tồn kho trong lô nguyên liệu
    UPDATE LO_NGUYEN_LIEU
    SET SoLuongConLai = SoLuongConLai - p_SoLuongHuy
    WHERE MaLo = p_MaLo;

    -- Lưu ý: Trigger TRG_CAPNHAT_DONGIA_BINHQUAN sẽ tự động chạy để update tổng tồn kho ở bảng NGUYEN_LIEU

    COMMIT;
    p_KetQua := N'Thành công';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

CREATE OR REPLACE TYPE T_CHI_TIET_PN_FULL AS OBJECT (
    MaNguyenLieu     NUMBER,
    MaLoaiNguyenLieu NUMBER,
    TenNguyenLieu    NVARCHAR2(100),
    DonViTinh        NVARCHAR2(50),
    NhaCungCap       NVARCHAR2(100),
    DinhLuong        NUMBER(10,2),
    SoLuong          NUMBER,
    GiaTruocThue     NUMBER,
    Thue_GTGT        NUMBER(5,2),
    TienThue         NUMBER,
    ThanhTien        NUMBER,
    NguongCanhBao    NUMBER,
    HanSuDung        VARCHAR2(20)
);
/

CREATE OR REPLACE TYPE T_LIST_CHI_TIET_PN_FULL AS TABLE OF T_CHI_TIET_PN_FULL;
/
CREATE OR REPLACE PROCEDURE SP_LAP_PHIEU_NHAP_FULL (
    p_MaTaiKhoan   IN NUMBER,
    p_DanhSach     IN T_LIST_CHI_TIET_PN_FULL,
    p_NgayNhap     IN DATE,
    p_GhiChu       IN NVARCHAR2,
    p_MaPhieuNhap_Out OUT NUMBER
)
AS
    v_TongGiaTri NUMBER := 0;
    v_MaNL_ThucTe NUMBER;
    v_Check_Ingredient NUMBER := 0;
    v_HanSuDung_Date DATE;
    v_SoLuongQuyDoi NUMBER(15,2);
BEGIN
    -- 1. Tính tổng giá trị phiếu nhập
    IF p_DanhSach IS NOT NULL AND p_DanhSach.COUNT > 0 THEN
        FOR i IN 1 .. p_DanhSach.COUNT LOOP
            v_TongGiaTri := v_TongGiaTri + p_DanhSach(i).ThanhTien;
        END LOOP;
    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Phiếu nhập phải có ít nhất 1 chi tiết nguyên liệu!');
    END IF;

    -- 2. Tạo Phiếu Nhập Kho trước để lấy Mã Phiếu
    INSERT INTO PHIEU_NHAP_KHO (MaTaiKhoan, NgayNhap, TongGiaTri, GhiChu)
    VALUES (p_MaTaiKhoan, p_NgayNhap, v_TongGiaTri, p_GhiChu)
    RETURNING MaPhieuNhap INTO p_MaPhieuNhap_Out;

    -- 3. Xử lý từng dòng chi tiết
    FOR i IN 1 .. p_DanhSach.COUNT LOOP
        IF p_DanhSach(i).HanSuDung IS NOT NULL AND TRIM(p_DanhSach(i).HanSuDung) IS NOT NULL THEN
            v_HanSuDung_Date := TO_DATE(p_DanhSach(i).HanSuDung, 'YYYY-MM-DD');
        ELSE
            v_HanSuDung_Date := NULL;
        END IF;

        v_SoLuongQuyDoi := p_DanhSach(i).SoLuong * p_DanhSach(i).DinhLuong;

        -- A. Master Data - KIỂM TRA TỒN TẠI
        SELECT COUNT(*) INTO v_Check_Ingredient FROM NGUYEN_LIEU
        WHERE UPPER(TenNguyenLieu) = UPPER(p_DanhSach(i).TenNguyenLieu);

        IF v_Check_Ingredient = 0 THEN
            -- [ĐÃ SỬA] KHÔNG TỰ ĐỘNG TẠO MỚI NỮA, MÀ BÁO LỖI LUÔN
            RAISE_APPLICATION_ERROR(-20002, 'Nguyên liệu [' || p_DanhSach(i).TenNguyenLieu || '] chưa có trong Danh mục gốc. Vui lòng thêm nguyên liệu trước khi nhập kho!');
        ELSE
            SELECT MaNguyenLieu INTO v_MaNL_ThucTe FROM NGUYEN_LIEU
            WHERE UPPER(TenNguyenLieu) = UPPER(p_DanhSach(i).TenNguyenLieu) AND ROWNUM = 1;
        END IF;

        -- B. Chi tiết Phiếu nhập
        INSERT INTO CHI_TIET_PHIEU_NHAP (
            MaPhieuNhap, MaNguyenLieu, SoLuong, GiaTruocThue, TienThue, DinhLuong, ThanhTien
        ) VALUES (
            p_MaPhieuNhap_Out, v_MaNL_ThucTe, p_DanhSach(i).SoLuong, p_DanhSach(i).GiaTruocThue,
            p_DanhSach(i).TienThue, p_DanhSach(i).DinhLuong, p_DanhSach(i).ThanhTien
        );

        -- C. Lô Nguyên Liệu
        INSERT INTO LO_NGUYEN_LIEU (
            MaNguyenLieu, MaPhieuNhap, NhaCungCap, SoLuongBanDau, SoLuongConLai, DonGiaQuyDoi, HanSuDung
        ) VALUES (
            v_MaNL_ThucTe, p_MaPhieuNhap_Out, p_DanhSach(i).NhaCungCap, v_SoLuongQuyDoi, v_SoLuongQuyDoi,
            ROUND(p_DanhSach(i).ThanhTien / NULLIF(v_SoLuongQuyDoi, 0), 2), v_HanSuDung_Date
        );
    END LOOP;

    COMMIT;
END;
/
-- SỬA NGUYÊN LIỆU
CREATE OR REPLACE PROCEDURE SP_SUA_NGUYEN_LIEU (
    p_MaNguyenLieu IN NUMBER,
    p_TenMoi       IN NVARCHAR2,
    p_DvtMoi       IN NVARCHAR2,
    p_TonMoi       IN NUMBER,
    p_NguongMoi    IN NUMBER,
    p_MaTaiKhoan   IN NUMBER,
    p_LyDo         IN NVARCHAR2,
    p_KetQua       OUT NVARCHAR2
)
IS
    v_TenCu    NGUYEN_LIEU.TenNguyenLieu%TYPE;
    v_DvtCu    NGUYEN_LIEU.DonViTinh%TYPE;
    v_TonCu    NGUYEN_LIEU.SoLuongTon%TYPE;
    v_NguongCu NGUYEN_LIEU.NguongCanhBao%TYPE;
BEGIN
    -- 1. Lấy dữ liệu cũ hiện tại trong kho
    SELECT TenNguyenLieu, DonViTinh, SoLuongTon, NguongCanhBao
    INTO v_TenCu, v_DvtCu, v_TonCu, v_NguongCu
    FROM NGUYEN_LIEU
    WHERE MaNguyenLieu = p_MaNguyenLieu;

    -- 2. Kiểm tra và Ghi log cho từng trường bị thay đổi
    IF v_TenCu != p_TenMoi THEN
        INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong, DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
        VALUES (p_MaTaiKhoan, N'Sửa dữ liệu', 'NGUYEN_LIEU', p_MaNguyenLieu, v_TenCu, p_TenMoi, p_LyDo, SYSDATE);
    END IF;

    IF v_DvtCu != p_DvtMoi THEN
        INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong, DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
        VALUES (p_MaTaiKhoan, N'Sửa dữ liệu', 'NGUYEN_LIEU', p_MaNguyenLieu, v_DvtCu, p_DvtMoi, p_LyDo, SYSDATE);
    END IF;

    IF v_TonCu != p_TonMoi THEN
        INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong, DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
        VALUES (p_MaTaiKhoan, N'Sửa dữ liệu', 'NGUYEN_LIEU', p_MaNguyenLieu, TO_CHAR(v_TonCu), TO_CHAR(p_TonMoi), p_LyDo, SYSDATE);
    END IF;

    IF v_NguongCu != p_NguongMoi THEN
        INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong, DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
        VALUES (p_MaTaiKhoan, N'Sửa dữ liệu', 'NGUYEN_LIEU', p_MaNguyenLieu, TO_CHAR(v_NguongCu), TO_CHAR(p_NguongMoi), p_LyDo, SYSDATE);
    END IF;

    -- 3. Cập nhật dữ liệu mới vào bảng Nguyên Liệu
    UPDATE NGUYEN_LIEU
    SET TenNguyenLieu = p_TenMoi,
        DonViTinh = p_DvtMoi,
        SoLuongTon = p_TonMoi,
        NguongCanhBao = p_NguongMoi
    WHERE MaNguyenLieu = p_MaNguyenLieu;

    COMMIT;
    p_KetQua := N'Thành công';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

-- XÓA NGUYÊN LIỆU
CREATE OR REPLACE PROCEDURE SP_XOA_NGUYEN_LIEU (
    p_MaNguyenLieu IN NUMBER,
    p_MaTaiKhoan   IN NUMBER,
    p_LyDo         IN NVARCHAR2,
    p_KetQua       OUT NVARCHAR2
)
IS
    v_DuLieuCu VARCHAR2(4000);
    v_Count_CT NUMBER := 0;
    v_Count_Topping NUMBER := 0;
    v_Count_Lo NUMBER := 0;
    v_DanhSachCT NVARCHAR2(2000);
    v_DanhSachTopping NVARCHAR2(2000);
    v_ThongBao NVARCHAR2(4000) := '';
BEGIN
    -- 1. Lấy dữ liệu cũ để lưu Log
    SELECT 'Tên: ' || TenNguyenLieu || '; ĐVT: ' || DonViTinh || '; Tồn kho: ' || SoLuongTon || '; Ngưỡng: ' || NguongCanhBao
    INTO v_DuLieuCu
    FROM NGUYEN_LIEU
    WHERE MaNguyenLieu = p_MaNguyenLieu;

    -- 2. Kiểm tra ràng buộc CÔNG THỨC
    SELECT COUNT(*) INTO v_Count_CT FROM CONG_THUC WHERE MaNguyenLieu = p_MaNguyenLieu;
    IF v_Count_CT > 0 THEN
        SELECT LISTAGG(TenSanPham, ', ') WITHIN GROUP (ORDER BY TenSanPham)
        INTO v_DanhSachCT
        FROM (
            SELECT DISTINCT sp.TenSanPham 
            FROM CONG_THUC ct 
            JOIN BIEN_THE bt ON ct.MaBienThe = bt.MaBienThe 
            JOIN SAN_PHAM sp ON bt.MaSanPham = sp.MaSanPham 
            WHERE ct.MaNguyenLieu = p_MaNguyenLieu
        );
        
        v_ThongBao := 'Nguyên liệu vẫn còn cấu hình trong công thức: ' || v_DanhSachCT;
    END IF;

    -- 3. Kiểm tra ràng buộc TOPPING
    SELECT COUNT(*) INTO v_Count_Topping FROM TOPPING WHERE MaNguyenLieuTru = p_MaNguyenLieu;
    IF v_Count_Topping > 0 THEN
        SELECT LISTAGG(TenTopping, ', ') WITHIN GROUP (ORDER BY TenTopping)
        INTO v_DanhSachTopping
        FROM (
            SELECT DISTINCT TenTopping
            FROM TOPPING 
            WHERE MaNguyenLieuTru = p_MaNguyenLieu
        );
        
        IF v_ThongBao IS NOT NULL AND LENGTH(v_ThongBao) > 0 THEN
            v_ThongBao := v_ThongBao || CHR(10) || 'Nguyên liệu vẫn còn gán với topping: ' || v_DanhSachTopping;
        ELSE
            v_ThongBao := 'Nguyên liệu vẫn còn gán với topping: ' || v_DanhSachTopping;
        END IF;
    END IF;

    IF v_ThongBao IS NOT NULL AND LENGTH(v_ThongBao) > 0 THEN
        p_KetQua := v_ThongBao;
        RETURN;
    END IF;

    -- 4. Kiểm tra xem đã bán/tiêu hao chưa (Lô hàng có SoLuongBanDau > SoLuongConLai)
    SELECT COUNT(*) INTO v_Count_Lo FROM LO_NGUYEN_LIEU 
    WHERE MaNguyenLieu = p_MaNguyenLieu AND SoLuongBanDau > SoLuongConLai;

    IF v_Count_Lo > 0 THEN
        -- Đã bán (Đã tiêu hao) -> XÓA MỀM
        UPDATE NGUYEN_LIEU SET DaXoa = 1 WHERE MaNguyenLieu = p_MaNguyenLieu;
        
        INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong,
                                        DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
        VALUES (p_MaTaiKhoan, 'Xóa mềm dữ liệu', 'NGUYEN_LIEU', p_MaNguyenLieu,
                v_DuLieuCu, 'DaXoa=1', p_LyDo, SYSDATE);
    ELSE
        -- Chưa bán -> XÓA CỨNG (Xóa sạch từ Lô hàng, Chi tiết phiếu nhập)
        DELETE FROM CHI_TIET_PHIEU_NHAP WHERE MaNguyenLieu = p_MaNguyenLieu;
        DELETE FROM LO_NGUYEN_LIEU WHERE MaNguyenLieu = p_MaNguyenLieu;
        DELETE FROM NGUYEN_LIEU WHERE MaNguyenLieu = p_MaNguyenLieu;

        INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong,
                                        DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
        VALUES (p_MaTaiKhoan, 'Xóa cứng dữ liệu', 'NGUYEN_LIEU', p_MaNguyenLieu,
                v_DuLieuCu, NULL, p_LyDo, SYSDATE);
    END IF;

    COMMIT;
    p_KetQua := 'Thành công';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_KetQua := 'Lỗi hệ thống: ' || SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_XOA_PHIEU_NHAP (
    p_MaPhieuNhap IN NUMBER,
    p_MaTaiKhoan  IN NUMBER,
    p_LyDo        IN NVARCHAR2,
    p_KetQua      OUT NVARCHAR2
)
IS
    v_DuLieuCu   CLOB;
    v_NgayNhap   DATE;
    v_TongGiaTri NUMBER;
    v_GhiChu     VARCHAR2(255);
    v_Count      NUMBER;
BEGIN
    -- 0. Kiểm tra phiếu nhập có tồn tại không (Ví dụ có 2 người cùng thao tác)
    SELECT COUNT(*) INTO v_Count
    FROM PHIEU_NHAP_KHO
    WHERE MaPhieuNhap = p_MaPhieuNhap;

    IF v_Count = 0 THEN
        p_KetQua := N'Lỗi: Không tìm thấy phiếu nhập này trong hệ thống.';
        RETURN;
    END IF;

    -- 1. Trích xuất thông tin Phiếu nhập để làm dữ liệu cũ (DuLieuCu)
    SELECT NgayNhap, TongGiaTri, GhiChu
    INTO v_NgayNhap, v_TongGiaTri, v_GhiChu
    FROM PHIEU_NHAP_KHO
    WHERE MaPhieuNhap = p_MaPhieuNhap;

    v_DuLieuCu := 'Ngày nhập: ' || TO_CHAR(v_NgayNhap, 'DD/MM/YYYY') ||
                  '; Tổng tiền: ' || v_TongGiaTri ||
                  '; Ghi chú: ' || v_GhiChu;

    -- 2. Ghi Log hệ thống
    INSERT INTO NHAT_KY_HE_THONG (MaTaiKhoan, HanhDong, TenBang, MaDoiTuong,
                                DuLieuCu, DuLieuMoi, LyDo, ThoiDiemThucHien)
    VALUES (p_MaTaiKhoan, N'Xóa dữ liệu', 'PHIEU_NHAP_KHO', p_MaPhieuNhap,
                v_DuLieuCu, NULL, p_LyDo, CURRENT_TIMESTAMP);

    -- 3. Cập nhật lại số lượng tồn kho (QUAN TRỌNG: Lấy số lượng từ phiếu nhập để trừ đi)
    FOR item IN (SELECT MaNguyenLieu, SoLuong
                 FROM CHI_TIET_PHIEU_NHAP
                 WHERE MaPhieuNhap = p_MaPhieuNhap)
    LOOP
        UPDATE NGUYEN_LIEU
        SET SoLuongTon = SoLuongTon - item.SoLuong
        WHERE MaNguyenLieu = item.MaNguyenLieu;
    END LOOP;

    -- 4. Xóa dữ liệu ở bảng con (Chi tiết phiếu nhập)
    DELETE FROM CHI_TIET_PHIEU_NHAP
    WHERE MaPhieuNhap = p_MaPhieuNhap;

    -- 5. Xóa dữ liệu ở bảng cha (Phiếu nhập kho)
    DELETE FROM PHIEU_NHAP_KHO
    WHERE MaPhieuNhap = p_MaPhieuNhap;

    -- Hoàn tất giao dịch
    COMMIT;
    p_KetQua := N'Thành công';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        -- Nếu việc trừ tồn kho làm cho số lượng bị âm (vi phạm CHECK constraint SoLuongTon >= 0), nó sẽ báo lỗi tại đây và rollback toàn bộ.
        p_KetQua := N'Lỗi hệ thống: ' || SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_SAN_PHAM(
    p_TenSanPham     IN NVARCHAR2,
    p_ThueGTGT       IN NUMBER,
    p_TrangThai      IN NVARCHAR2,
    p_TenLoaiSanPham IN NVARCHAR2,
    p_MoTaSanPham    IN NVARCHAR2,
    p_TenAnhSanPham  IN NVARCHAR2,
    p_KieuDuLieuAnh  IN VARCHAR2,
    p_DuLieuAnh      IN BLOB,
    p_MaSanPham_OUT  OUT NUMBER
)
AS
    v_MaLoaiSanPham NUMBER;
BEGIN
    -- Lấy Mã Loại Sản Phẩm từ Tên Loại
    SELECT MaLoaiSanPham INTO v_MaLoaiSanPham
    FROM LOAI_SAN_PHAM WHERE TenLoaiSanPham = p_TenLoaiSanPham;

    -- Giá sản phẩm chỉ lưu ở biến thể (BIEN_THE), không lưu ở bảng SAN_PHAM nữa
    INSERT INTO SAN_PHAM (MaLoaiSanPham, TenSanPham, Thue_GTGT, TenAnhSanPham, KieuDuLieuAnh, DuLieuAnh, TrangThai, MoTa)
    VALUES (v_MaLoaiSanPham, p_TenSanPham, p_ThueGTGT, p_TenAnhSanPham, p_KieuDuLieuAnh, p_DuLieuAnh, p_TrangThai, p_MoTaSanPham)
    RETURNING MaSanPham INTO p_MaSanPham_OUT;

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_UPDATE_SAN_PHAM(
    p_MaSanPham      IN NUMBER,
    p_TenSanPham     IN NVARCHAR2,
    p_ThueGTGT       IN NUMBER,
    p_TenAnhSanPham  IN NVARCHAR2,
    p_KieuDuLieuAnh  IN VARCHAR2,
    p_DuLieuAnh      IN BLOB,
    p_TrangThai      IN NVARCHAR2,
    p_TenLoaiSanPham IN NVARCHAR2
)
AS
    v_MaLoaiSanPham NUMBER;
BEGIN
    -- Lấy Mã Loại Sản Phẩm từ Tên Loại
    SELECT MaLoaiSanPham INTO v_MaLoaiSanPham
    FROM LOAI_SAN_PHAM WHERE TenLoaiSanPham = p_TenLoaiSanPham;

    -- Giá sản phẩm không còn lưu ở bảng SAN_PHAM nữa (chỉ lưu ở BIEN_THE)
    -- Nếu người dùng có chọn ảnh mới thì cập nhật cả ảnh
    IF p_DuLieuAnh IS NOT NULL THEN
        UPDATE SAN_PHAM
        SET MaLoaiSanPham = v_MaLoaiSanPham,
            TenSanPham = p_TenSanPham,
            Thue_GTGT = p_ThueGTGT,
            TenAnhSanPham = p_TenAnhSanPham,
            KieuDuLieuAnh = p_KieuDuLieuAnh,
            DuLieuAnh = p_DuLieuAnh,
            TrangThai = p_TrangThai
        WHERE MaSanPham = p_MaSanPham;
    ELSE
        -- Nếu không chọn ảnh mới thì giữ nguyên ảnh cũ
        UPDATE SAN_PHAM
        SET MaLoaiSanPham = v_MaLoaiSanPham,
            TenSanPham = p_TenSanPham,
            Thue_GTGT = p_ThueGTGT,
            TrangThai = p_TrangThai
        WHERE MaSanPham = p_MaSanPham;
    END IF;

    COMMIT;
END;

CREATE OR REPLACE TRIGGER TRG_CAPNHAT_DONGIA_BINHQUAN
FOR INSERT OR UPDATE OR DELETE ON LO_NGUYEN_LIEU
COMPOUND TRIGGER

    -- Khai báo mảng để lưu danh sách các mã nguyên liệu bị thay đổi.
    -- Dùng mảng băm (associative array) để tự động loại bỏ các mã trùng lặp (vd: nhập 1 lúc 5 lô của cùng 1 NL).
    TYPE t_nguyen_lieu IS TABLE OF BOOLEAN INDEX BY PLS_INTEGER;
    v_nguyen_lieu_map t_nguyen_lieu;
    v_ma_nl PLS_INTEGER;

    -- 1. Giai đoạn AFTER EACH ROW (Kích hoạt sau mỗi dòng bị tác động)
    -- Mục đích: Ghi nhận lại Mã Nguyên Liệu nào vừa bị thêm/sửa/xóa lô hàng.
    AFTER EACH ROW IS
    BEGIN
        IF INSERTING OR UPDATING THEN
            v_nguyen_lieu_map(:NEW.MaNguyenLieu) := TRUE;
        END IF;

        -- Xử lý thêm trường hợp xóa lô hoặc thay đổi mã NL của lô (dù hiếm)
        IF DELETING OR (UPDATING AND :OLD.MaNguyenLieu != :NEW.MaNguyenLieu) THEN
            v_nguyen_lieu_map(:OLD.MaNguyenLieu) := TRUE;
        END IF;
    END AFTER EACH ROW;

    -- 2. Giai đoạn AFTER STATEMENT (Kích hoạt 1 lần duy nhất sau khi toàn bộ câu lệnh chạy xong)
    -- Mục đích: Tính toán lại tổng số lượng và đơn giá bình quân, sau đó cập nhật bảng NGUYEN_LIEU.
    AFTER STATEMENT IS
        v_tong_gia_tri NUMBER(15, 2);
        v_tong_so_luong NUMBER(15, 2);
        v_don_gia_bq NUMBER(15, 2);
    BEGIN
        -- Lấy mã nguyên liệu đầu tiên trong mảng
        v_ma_nl := v_nguyen_lieu_map.FIRST;

        -- Duyệt qua từng nguyên liệu đã bị ảnh hưởng
        WHILE v_ma_nl IS NOT NULL LOOP

            -- Tính tổng giá trị và tổng số lượng tồn của nguyên liệu đó từ các lô hàng
            SELECT NVL(SUM(SoLuongConLai * DonGiaQuyDoi), 0),
                   NVL(SUM(SoLuongConLai), 0)
            INTO v_tong_gia_tri, v_tong_so_luong
            FROM LO_NGUYEN_LIEU
            WHERE MaNguyenLieu = v_ma_nl
              AND SoLuongConLai > 0; -- Chỉ tính những lô đang còn hàng

            -- Tính đơn giá bình quân
            IF v_tong_so_luong > 0 THEN
                v_don_gia_bq := v_tong_gia_tri / v_tong_so_luong;
            ELSE
                v_don_gia_bq := 0; -- Nếu kho hết sạch hàng thì trả về 0
            END IF;

            -- Cập nhật vào bảng NGUYEN_LIEU
            -- Tiện thể: Trigger tự cập nhật luôn SoLuongTon để kho tổng tự động đồng bộ với chi tiết các lô
            UPDATE NGUYEN_LIEU
            SET DonGiaBinhQuan = v_don_gia_bq,
                SoLuongTon = v_tong_so_luong
            WHERE MaNguyenLieu = v_ma_nl;

            -- Chuyển sang nguyên liệu tiếp theo trong mảng
            v_ma_nl := v_nguyen_lieu_map.NEXT(v_ma_nl);
        END LOOP;

        -- Xóa mảng để giải phóng bộ nhớ
        v_nguyen_lieu_map.DELETE;
    END AFTER STATEMENT;

END TRG_CAPNHAT_DONGIA_BINHQUAN;
/


INSERT INTO CHUC_NANG (MaChucNang, TenChucNang) VALUES (1, N'Khách hàng');
INSERT INTO CHUC_NANG (MaChucNang, TenChucNang) VALUES (2, N'Menu đồ uống');
INSERT INTO CHUC_NANG (MaChucNang, TenChucNang) VALUES (3, N'Nhập kho');

INSERT INTO CHUC_NANG (MaChucNang, TenChucNang) VALUES (5, N'Phân quyền');
INSERT INTO CHUC_NANG (MaChucNang, TenChucNang) VALUES (6, N'Bán hàng');
INSERT INTO CHUC_NANG (MaChucNang, TenChucNang) VALUES (7, N'Quản lý đơn hàng');
INSERT INTO CHUC_NANG (MaChucNang, TenChucNang) VALUES (8, N'Báo cáo và thống kê');
INSERT INTO CHUC_NANG (MaChucNang, TenChucNang) VALUES (9, N'Cấu hình tích điểm');

INSERT INTO NGUOI_DUNG (HoTen, Email, SoDienThoai)
VALUES (N'Nguyễn Minh Nhựt', N'24521369@gm.uit.edu.vn', 0968638923);

INSERT INTO TAI_KHOAN (MaNguoiDung, TenDangNhap, MatKhauDaMaHoa)
VALUES (1, N'admin', N'8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92');


INSERT INTO PHAM_VI_QUYEN (TenPhamVi, MaChucNang, Them, Sua, Xoa, Xem, XuatFile)
VALUES ('FULL QUYỀN KHÁCH HÀNG', 1, 1,1,1,1,1);
INSERT INTO PHAM_VI_QUYEN (TenPhamVi, MaChucNang, Them, Sua, Xoa, Xem, XuatFile)
VALUES ('FULL QUYỀN THỰC ĐƠN', 2, 1,1,1,1,1);
INSERT INTO PHAM_VI_QUYEN (TenPhamVi, MaChucNang, Them, Sua, Xoa, Xem, XuatFile)
VALUES ('FULL QUYỀN NHẬP KHO', 3, 1,1,1,1,1);

INSERT INTO PHAM_VI_QUYEN (TenPhamVi, MaChucNang, Them, Sua, Xoa, Xem, XuatFile)
VALUES ('FULL QUYỀN PHÂN QUYỀN', 5, 1,1,1,1,1);
INSERT INTO PHAM_VI_QUYEN (TenPhamVi, MaChucNang, Them, Sua, Xoa, Xem, XuatFile)
VALUES ('FULL QUYỀN BÁN HÀNG', 6, 1,1,1,1,1);
INSERT INTO PHAM_VI_QUYEN (TenPhamVi, MaChucNang, Them, Sua, Xoa, Xem, XuatFile)
VALUES ('FULL QUYỀN QUẢN LÝ ĐƠN HÀNG', 7, 1,1,1,1,1);
INSERT INTO PHAM_VI_QUYEN (TenPhamVi, MaChucNang, Them, Sua, Xoa, Xem, XuatFile)
VALUES ('FULL QUYỀN THỐNG KÊ', 8, 1,1,1,1,1);
INSERT INTO PHAM_VI_QUYEN (TenPhamVi, MaChucNang, Them, Sua, Xoa, Xem, XuatFile)
VALUES ('FULL QUYỀN CẤU HÌNH TÍCH ĐIỂM', 9, 1,1,1,1,1);


INSERT INTO PHAN_QUYEN_TAI_KHOAN (MaTaiKhoan, MaPhamVi) values (1, 1);
INSERT INTO PHAN_QUYEN_TAI_KHOAN (MaTaiKhoan, MaPhamVi) values (1, 2);
INSERT INTO PHAN_QUYEN_TAI_KHOAN (MaTaiKhoan, MaPhamVi) values (1, 3);

INSERT INTO PHAN_QUYEN_TAI_KHOAN (MaTaiKhoan, MaPhamVi) values (1, 5);
INSERT INTO PHAN_QUYEN_TAI_KHOAN (MaTaiKhoan, MaPhamVi) values (1, 6);
INSERT INTO PHAN_QUYEN_TAI_KHOAN (MaTaiKhoan, MaPhamVi) values (1, 7);
INSERT INTO PHAN_QUYEN_TAI_KHOAN (MaTaiKhoan, MaPhamVi) values (1, 8);
INSERT INTO PHAN_QUYEN_TAI_KHOAN (MaTaiKhoan, MaPhamVi) values (1, 9);

COMMIT;

-- 27. LICH_LAM_VIEC
CREATE TABLE LICH_LAM_VIEC (
    MaLich NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan NUMBER NOT NULL,
    NgayLamViec DATE NOT NULL,
    LoaiCa NVARCHAR2(20) NOT NULL CHECK (LoaiCa IN (N'Sáng', N'Chiều')),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan),
    CONSTRAINT UQ_LICH_LAM_VIEC UNIQUE (MaTaiKhoan, NgayLamViec, LoaiCa)
);

INSERT INTO CHUC_NANG (MaChucNang, TenChucNang) VALUES (10, N'Xếp lịch nhân viên');
INSERT INTO PHAM_VI_QUYEN (TenPhamVi, MaChucNang, Them, Sua, Xoa, Xem, XuatFile) VALUES ('FULL QUYỀN XẾP LỊCH NV', 10, 1,1,1,1,1);
INSERT INTO PHAN_QUYEN_TAI_KHOAN (MaTaiKhoan, MaPhamVi) VALUES (1, (SELECT MaPhamVi FROM PHAM_VI_QUYEN WHERE MaChucNang = 10 AND ROWNUM = 1));

COMMIT;
